### ISSUE TITLE
Truncated View of Properties with "Plus" next to it...

### ISSUE THREAD

**Issue by Jaben** [datalust/seq-releases#119]
Starting to get huge properties that actually take a few seconds to load. Nice to have Seq detect these and truncate them allowing you to click "plus" next to a "..." to load the whole thing.

**Comment by nblumhardt** [comment]
Small enhancement that might help with usability, but won't improve load time, is #314, coming in 2.2.

**Comment by nblumhardt** [comment]
#314 should have helped with the display issue - any improvement on that front?

If load times aren't improved by that change, please let me know and I'll re-title this ticket to cover that aspect. Thanks!

**Comment by Jaben** [comment]
@nblumhardt hah, I just thought you fixed this a long time ago -- didn't see your response. Yeah, what you have now is great. 👍
