### ISSUE TITLE
Occationally Check Apps -- Display if They Can Be Updated

### ISSUE THREAD

**Issue by Jaben** [datalust/seq-releases#167]
Just updated Seq.App.YouTrack to v0.5. Problem is... I doubt anyone will notice. Would be nice if it occasionally checked for updates.

**Comment by nblumhardt** [comment]
The next Seq version will include some update checking infrastructure (initially a check for new Seq versions) that will eventually be extended to handle this feature.

**Comment by andymac4182** [comment]
It would be great if this could also put a log into Seq so that I can have another application such as a Slack bot post a message to slack notifying me and allowing me to update using the buttons support in slack.

**Comment by nblumhardt** [comment]
In 3.4, there is now a "Check for package updates" setting and an "Update" button that will be displayed when app updates are available.

![image](https://cloud.githubusercontent.com/assets/342712/20167696/dc064e0e-a768-11e6-89e8-b06e291d927d.png)

**Comment by Jaben** [comment]
👍
