### ISSUE TITLE
Asynchronous buffer flushing mode for the log4net appender

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#190]
> nblumhardt commented on Apr 11
> While the appender does buffer messages, the flushing process is synchronous (allowing the non-lossy mode to work correctly by default).
> We should also support an 'is async' flag that performs the flush on a worker thread, to minimize latency in the calling app.

Migrated from https://github.com/continuousit/seq-client/issues/11

**Comment by pitermarx** [comment]
would you reconsider this?

**Comment by nblumhardt** [comment]
Hi Pedro - yes, absolutely. I am not sure when the time can be allocated though. I will reopen in case someone is able to send a PR for it. Thanks!

**Comment by pitermarx** [comment]
After some though, I got this idea:
If i set the bufferSize to anything other than 1, the appender will have to be be async right?

**Comment by nblumhardt** [comment]
@pitermarx not precisely; when the buffer size is, say, 100, the first 99 events will be queued, and on the 100th write there will be a synchronous flush (IIRC).

**Comment by pitermarx** [comment]
I think ill use this https://github.com/cjbhaines/Log4Net.Async
instead of a new implementation

**Comment by nblumhardt** [comment]
Thanks for the link, looks like a great option 👍
