### ISSUE TITLE
Alter Time Format

### ISSUE THREAD

**Issue by richardlawley** [datalust/seq-releases#246]
I would like to be able to alter the time format being displayed in Seq.  There are two reasons:
- Examining sub-second times more easily (I have to hover over the times to view milliseconds at the moment).
- Removing clutter by removing time zone

**Comment by nblumhardt** [comment]
Hi Richard - thanks for the input! I can see customising the format would to include milliseconds would make a useful option.

You should be able to get rid of some clutter including the timezone using these settings (click your username, then _Preferences_):

![image](https://cloud.githubusercontent.com/assets/342712/5636589/516e183a-963f-11e4-8bd5-5c87d22afd52.png)

**Comment by CaseyBurnsSv** [comment]
We want to see the milliseconds too.

**Comment by nblumhardt** [comment]
Version 2 (coming shortly) will default to milliseconds display, and use local time/24hr.

![image](https://cloud.githubusercontent.com/assets/342712/7466418/d12628cc-f325-11e4-9a70-21552479aad5.png)

I'm not sure yet how much customization will be initially supported, but I think this makes a better default. Cheers!

**Comment by richardlawley** [comment]
This default removes any further need I had for customisation, thanks.

**Comment by nblumhardt** [comment]
Thanks Richard. Leaving this open, since somewhere in the early 2.0 cycle I think we'll support [moment](http://momentjs.com/) format specifiers anyway :)

**Comment by richardlawley** [comment]
Related to this would be formatting the times in the time range specifier using local formats instead of fixed US format too:

![image](https://cloud.githubusercontent.com/assets/1608083/8207250/0250ce90-14f8-11e5-9276-f6d06104a008.png)

Not sure if this should be a separate issue, since it's not actually related to the original location.

**Comment by nblumhardt** [comment]
Thanks again for the ticket Richard. #396 covers the date formatting in charts and other places. Cheers!
