### ISSUE TITLE
No word wrap on exception message text forces user to scroll horizontally

### ISSUE THREAD

**Issue by redwards510** [datalust/seq-releases#319]
![image](https://cloud.githubusercontent.com/assets/8303176/8576841/95c0de6a-2559-11e5-8b7e-0eba46af2a9f.png)

I have to read a lot of exceptions in Seq. It's frustrating to have to read long exception messages by scrolling horizontally. usually I drag'n'select the line, copy it to clipboard, then paste that into a text editor. That's a lot of steps!

I think the attached image illustrates what I mean.  I'm not sure how to solve this one. Maybe instead of dumping the whole exception to a single pane you could extract just exception.Message and make that it's own searchable field on it's own line and word wrap it. I realize if you word wrapped the entire exception the stack trace would get pretty difficult to read. 

Affects Seq 2.1.22

**Comment by nblumhardt** [comment]
Thanks Ryan. I think the key might be for Seq to parse the exception property, and intelligently lay out the message and (separate) stack trace. (Sounds like a fun programming challenge, anyway ;-))

I'll have a look at this in the next (2.3) cycle. Appreciate the feedback, as always!

**Comment by nblumhardt** [comment]
In the end, just wrapping turns out to be fine here.

![image](https://cloud.githubusercontent.com/assets/342712/20124481/76230362-a672-11e6-9783-b36b15a25f4c.png)
