### ISSUE TITLE
Query extension: Keep rows related to my filter

### ISSUE THREAD

**Issue by oliverjanik** [datalust/seq-releases#340]
I played around with the Query syntax a bit and here's a use case I'm missing:

I filter by certain event type e.g. a specific error that's occurring in the system. Each event has a RequestId attached. Now I would love to get all the events of the same type with related events based on RequestId. Almost a join like behaviour.

Is such a thing possible?

**Comment by nblumhardt** [comment]
Hi Oliver - this would be a cool feature. Nothing of this kind today, but something I'll give some thought to down the track now that you've pointed it out. Thanks!

**Comment by nblumhardt** [comment]
Hi Oliver - still interested in following up on this one, but moving it to the UserVoice list for now to keep the tracker more focused: https://seq.uservoice.com/forums/268188-general/suggestions/17018038-query-extension-keep-rows-related-to-my-filter - thanks!
