### ISSUE TITLE
Suggestion: Add an extendibility point to provide external links to the panel displaying action for an event

### ISSUE THREAD

**Issue by AntoineGa** [datalust/seq-releases#360]
Hi, Seq is fantastic.
I mainly use it to log events and display them using an external web server and d3js to provide visualization.
But i can't find a way to integrate easily the links within the UI.

My suggestion is to provide a configuration point or an extensibility through Seq App to add a link 
- enabled / displayed based on a Predicate provided and evaluated using the event
- built from the event

thanks

**Comment by nblumhardt** [comment]
Hi Antoine,

In this case do you mean providing a hyperlink from your own app back to the Seq UI?

Best regards,
Nick

**Comment by AntoineGa** [comment]
Hi Nicholas !

I need a way to generate a custom link per event, depending on the data of the event in the Seq UI.

I don't know how to do this, and i was wondering if it can be through configuration, or if it's a valid use case for Seq App.
Right now i don't know if it's feasible.

**Comment by AntoineGa** [comment]
the goal is to generate through an hyperlink on the Seq Ui and based on a property of an event a diagram like this : http://knsv.github.io/mermaid/live_editor/#/view/c2VxdWVuY2VEaWFncmFtCkEtPj4gQjogUXVlcnkKQi0-PiBDOiBGb3J3YXJkIHF1ZXJ5Ck5vdGUgcmlnaHQgb2YgQzogVGhpbmtpbmcuLi4KQy0-PiBCOiBSZXNwb25zZQpCLT4-IEE6IEZvcndhcmQgcmVzcG9uc2UK

I can generate this, i just miss the link on Seq UI to smooth user experience (right now i 'm copy-pasting the key to generate it)

**Comment by nblumhardt** [comment]
Thanks for all of the information. I would love to tackle this at some point, I don't think it will be in the next version or so however so as part of an issue-tracker triage I've moved it over to: https://seq.uservoice.com/forums/268188-general/suggestions/16912870-ui-extension-points. Cheers!
