### ISSUE TITLE
API key declaration "a posteriori"

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-releases#367]
Hi,

I've seen the blog post about  [remote Serilog level control](http://nblumhardt.com/2016/02/remote-level-control-in-serilog-using-seq/) and this sounds great ! 
But we have not used API keys so far in the applications we have deployed ... we will probably use it from now on, but thinking of the approach to do that, I thought it was maybe a bit tedious and there might be room from improvement.

To use API keys on many applications, If I understand correctly, the process currently : 
1. Go to_ Seq Settings_
2. Declare an application
3. Copy the _api Token_
4. go paste it in the application's config file

-> **Repeat _N * M_ times** , _N_ being the number of things we deploy (a component of an app) and _M_ being the number of environments we deploy to

I would love to see an approach where we just fill in some arbitrary string as a token in our app config files and **map it to the Api Key afterwards**. 

The process would be : 
1. I prepare my config file filling in an arbitrary token (ideally, something sensible and human readable like `MyApp.MyComponent-DeployEnvironment`) this could be done during deployment.
2. I deploy the app in its environment
3. in Seq, somewhere I can **see a list of Api Keys** used by clients that have not yet been "officially registered in Seq"
4. from there I can **promote an item of this list to an "official registered" API Key**, with all the goodies that apply (added properties, extra filter, level control)

The idea is that I can just register all those apps from one page instead of going back and forth between Seq and the config files.

It is my understanding that the **api Key** is not specially secret or anything, so the format does not have to be an obscure string.

Does this make sense ?

**Comment by nblumhardt** [comment]
Thanks for the thoughtful post, some great ideas here.

**Comment by nblumhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/342712/18538828/6b8fcd9c-7b55-11e6-8395-bb77c89986e1.png)

![image](https://cloud.githubusercontent.com/assets/342712/18538846/90a5c190-7b55-11e6-9815-7041606da57c.png)

![image](https://cloud.githubusercontent.com/assets/342712/18538856/ae5fe95e-7b55-11e6-8de4-20c0202af800.png)

**Comment by MathewsJosh** [comment]
Can I set the API key automatically in docker compose before build/up the container? And in a local environment?

**Comment by liammclennan** [comment]
@MathewsJosh you can set API keys via the API or CLI, which means that Seq must have already started.

**Comment by MathewsJosh** [comment]
My system is based on several microservice containers and I would like to centralize their logs in seq or another tool. This system will be deployed on each client's machine. Unfortunately, it's not possible to explain to each user how to create their own apikey in the frontend and manually change the api keys on local code.

In this case, is it possible to make this configuration in another way before building the container? Can you provide any alternative for this case?

**Comment by liammclennan** [comment]
@MathewsJosh you could create your own docker image based on the Seq image and customize it however you like. Or run a script as part of your installation.

It sounds like your scenario may not be compatible with the [Seq end user license agreement](https://datalust.co/doc/eula-current.pdf). I suggest checking that first.

**Comment by MathewsJosh** [comment]
Hi @liammclennan,

We are developing an open source project that will not be commercialized. Following your suggestion, we will try to customize a docker image based on Seq for our needs. Thanks for mentioning the license agreement - we will ensure compliance.

If you have any further insights or recommendations, feel free to share.
