### ISSUE TITLE
Default signal

### ISSUE THREAD

**Issue by kristofferlindvall** [datalust/seq-releases#379]
We have a signal that we consider "default" which applies some tags. I'd like this to behave like "None" meaning it should be enabled when no other signal is selected, but disabled as soon as any other signal is enabled. Basically overriding none.

**Comment by tsimbalar** [comment]
Is it similar to this request ? 
https://seq.uservoice.com/forums/268188-general/suggestions/8952343-configure-tags-independently-from-signals

**Comment by dsteinweg** [comment]
+1 to this request by @jansson.

However, I don't see a need to override the "None" behavior.  In my mind, merely choosing 0..n signals to be preselected when you load Seq would be great.  Clicking "None" will clear any signals that were preselected and is quick enough to do.  I also see this suggestion as separate from "tags".

Also, I'd think it'd make sense if preselected signals were user setting (each user can have different defaults).

**Comment by bratfizyk** [comment]
+1 - I'm also looking forward to have such a feature.
What I've been trying to achieve is to use Seq as a heartbeat processor (together with the Timeout app). It would be nice to hide heartbeat-related logs by default, instead of selecting the "hide-heartbeat" signal manually.

**Comment by tsimbalar** [comment]
as a workaround, an option is to just use the url with the proper signal already selected in your bookmarks :)

i.e. bookmark a url like http://localhost:5341/#/events?intersect=signal-33,signal-65

**Comment by nblumhardt** [comment]
Step 1...

![image](https://cloud.githubusercontent.com/assets/342712/19992124/e7541160-a286-11e6-9e2c-461080791bfd.png)

**Comment by nblumhardt** [comment]
Step 2, open the _events_ screen or press...

![image](https://cloud.githubusercontent.com/assets/342712/19993219/b9c559c6-a28f-11e6-861b-8acf2e737415.png)
