### ISSUE TITLE
Can't do comparison on properties that are sent as strings, but are ints

### ISSUE THREAD

**Issue by HakanL** [datalust/seq-releases#398]
Because of various reasons we have data sent to json with properties where the value is an int (think duration in seconds), but it has quotes around it in the json data. It's not always easy to change this so it's sent without quotes, so I'm suggestion that SEQ can interpret that (decimal.TryParse?) so you can still do < and > comparison on the content.

Example:
`    {
      "Name": "MethodDurationS",
      "Value": "314"
    },
`

**Comment by nblumhardt** [comment]
`ToNumber(Value)` will attempt to parse a string. If the value passed is already a number (e.g the log event schema was changed) then the number will be returned. Failed parsing will evaluate to 'undefined' (roughly SQL null semantics - all comparisons return false).
