### ISSUE TITLE
Option to display timestamp in UTC

### ISSUE THREAD

**Issue by HakanL** [datalust/seq-releases#399]
When troubleshooting events it would be very nice to see the timestamp in UTC. my user is configured for PST, which is good because that's the most common for me, but I would like to see for a particular message what timestamp it was on the server, which runs in UTC. Maybe some hover-over or something on the timestamp?

**Comment by nblumhardt** [comment]
Thanks for the suggestion, will check this out.

**Comment by nblumhardt** [comment]
Two additions here.

**A per-user option to always use UTC:**

![image](https://cloud.githubusercontent.com/assets/342712/19917107/f706b580-a10b-11e6-8be2-37a64c0b8b41.png)

**ISO 8601 on hover:**

![image](https://cloud.githubusercontent.com/assets/342712/19917180/97348d8e-a10c-11e6-87a7-b6eedf9c1ee9.png)

**Comment by HakanL** [comment]
Very nice, thank you!!

**Comment by nblumhardt** [comment]
Thanks - should have a preview build with this out in the next few days 👍
