### ISSUE TITLE
Add an option to show Diff next to the timestamp

### ISSUE THREAD

**Issue by HakanL** [datalust/seq-releases#400]
It should show the diff between the previous log entry, like +15s or something like that. Would make it easier to see duration between events.

**Comment by nblumhardt** [comment]
Great suggestion, thanks.

**Comment by nblumhardt** [comment]
@HakanL I'm a fan of this idea, but I think it will be for a future milestone. I've moved the ticket to: https://seq.uservoice.com/forums/268188-general/suggestions/16997971-add-an-option-to-show-diff-next-to-the-timestamp. Thanks!
