### ISSUE TITLE
"Add to Signals" is enabled for SQL queries when selecting query from history

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-releases#406]
As of Seq **v3.1.12-pre**, starting with en empty "filter text box" ... if I select a SQL query from the history ...
![seq-selectsqlfromhistory1](https://cloud.githubusercontent.com/assets/160544/14560145/05439c2c-030e-11e6-96e5-6e6e47b3df1f.png)

... then the button "add to signals" is enabled ...
![seq-selectsqlfromhistory2](https://cloud.githubusercontent.com/assets/160544/14560183/3258eafa-030e-11e6-8cad-d28a88b899b6.png)

and clicking on it adds it as a signal ... which does not make much sense ....
![seq-selectsqlfromhistory3](https://cloud.githubusercontent.com/assets/160544/14560196/50148202-030e-11e6-9b2b-008363a0bbd0.png)

**Comment by nblumhardt** [comment]
Thanks Thibaud; I don't think this'll squeeze in for the initial 3.1 but I'll queue it up for the first subsequent patch. Cheers!

**Comment by nblumhardt** [comment]
This one is fixed.
