### ISSUE TITLE
Tag order not respected when output. 

### ISSUE THREAD

**Issue by timgaunt** [datalust/seq-releases#411]
I've got a couple of tags on a signal and the order comes out the wrong way around (see below). We can work around this by adding them in reverse order but it would be better if it respected the order.

![image](https://cloud.githubusercontent.com/assets/254564/14781565/29b999e2-0adb-11e6-83ea-61774c50f91a.png)

**Comment by nblumhardt** [comment]
Done, with a sophisticated new colour scheme to boot :-)

Note, when multiple signals including the same tag are combined, one will still "win", so it's not a 100% watertight ordering.

![image](https://cloud.githubusercontent.com/assets/342712/15064628/b23211e8-1399-11e6-8d59-b8211168b352.png)
