### ISSUE TITLE
SQL queries / charting : handling missing values - COALESCE

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-releases#412]
_as of Seq v3.1.16_

Hi,

with the new charting features, I am now trying to show some statistics about response times : avg / min / max per day, for instance ... 

exemple : `select count(*) , mean(TotalMilliseconds(Duration)), min(TotalMilliseconds(Duration)), max(TotalMilliseconds(Duration))  from stream group by time(1d)`

The problem is on some days, there are no events, and therefore the aggregate operators (mean, min, max) all return null ... this makes the chart a bit hard to use ...

![seq-query-nulls](https://cloud.githubusercontent.com/assets/160544/14810350/c511a620-0b92-11e6-8b8b-2141cfccf963.png)

![seq-charts-nulls](https://cloud.githubusercontent.com/assets/160544/14810569/db7cd7bc-0b93-11e6-984a-3af4ea8ead27.png)

My goal is basically to make the data usable, in both the "**grid output**" and the "**charts**".

In the **grid output,** I'd like to find a way to say : "do not show the lines where mean or min or max is null ... or count =0" ... in SQL that would be a **`having`** clause, but I believe it is not supported in Seq yet ... 

In the charts, I'm not quite sure about what I would want to do ... probably 
- try to join the dots together while also indicating that there are actually no values in between ... (i.e in option in the charts view to say how to handle missing values)
- Maybe a decent approach would be to have a `COALESCE` function in the SQL query ... this would allow me to explicitely give "0" instead of "null" when there are no values ... and then I expect the chart would just show 0s for those values, without knowing that there were actually no values at all.

Does that make sense ? 

Thanks !

**Comment by nblumhardt** [comment]
Thanks Thibaud! I see the size of those dots needs to go up a px or two.. :-)

I initially thought about joining the dots, but it doesn't seem quite right. I checked the behaviour of Grafana and it matches the way Seq does it at the moment, so hopefully not totally without precedent.

`COALESCE` sounds like the right approach because it's under the user's control. Ultimately, if you don't have the data you don't get a nice chart, but at least with some way of controlling the fill things should look better. I'll consider this the `COALESCE` ticket and we should see where things land after that :+1:

**Comment by tsimbalar** [comment]
yep, COALESCE probably makes more sense for the charting part. Giving the user the control of the value is probably better.

Regarding the "grid results", though ... any chance we would get the "HAVING" ? :)

**Comment by nblumhardt** [comment]
#416 - voila! Aiming to make it into the next ver.

**Comment by nblumhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/342712/15063861/3136717c-1391-11e6-9550-4c31df6dcba4.png)

Important note - `coalesce()` in Seq accepts exactly two arguments, not a variable number as in the SQL function.

(Dots up a few px as well.)

**Comment by tsimbalar** [comment]
> Important note -  coalesce()  in Seq accepts exactly two arguments, not a variable number as in the SQL function.

ok ... so I guess it makes it a [`ISNULL()`](https://msdn.microsoft.com/en-us/library/ms184325.aspx) , i.e. the most badly named function in the world .... but let's keep the `COALESCE` name, it is so much clearer :)

**Comment by nblumhardt** [comment]
For now, yes :-) ... but hopefully the `n-args` limitation can be lifted in the future with some minor work.
