### ISSUE TITLE
Feature Request: Back Reference in Seq syntax

### ISSUE THREAD

**Issue by jackawatts** [datalust/seq-releases#413]
Analogous to Regex Backreferences.
eg. ($53231) && CorrelationId == 1.CorrelationId (where 1 is the backref)

Application:
Workflows: long and short
Finding errors and warnings on an arbitrary CorrelationId whether it is requestId, correlationid etc
Storing in views etc.

**Comment by nblumhardt** [comment]
Hi Jack - thanks again for suggesting this (I think we discussed it more over on the support site). It's a very interesting idea; I'm "grooming the backlog" so to speak and think this one will be better tracked over on UserVoice for now: https://seq.uservoice.com/forums/268188-general/suggestions/16896316-backreferences-in-filter-syntax

Hope all's going well, and cheers! :-)
