### ISSUE TITLE
Web App should use Websockets

### ISSUE THREAD

**Issue by raybooysen** [datalust/seq-releases#417]
Currently the web app (seems to) poll the server to retrieve new events.  This should use websockets and have the server push events to the web app.  This would stop any delay between events being logged and them appearing in the web app.

**Comment by nblumhardt** [comment]
Thanks for the suggestion. I've been keen to do this for some time, but there are some subtleties when there are a lot of events flowing through. The advantage of the current scheme is that it always takes the last `x` events from the stream. If there are only a few new events it's wasteful, but in the reverse scenario where thousands are flowing through each second, just grabbing the latest every few seconds works quite well. Still, something for us to consider afresh :+1:

**Comment by nblumhardt** [comment]
Quick update... It's unlikely this will be used by the web app in 3.4, but the foundations for streaming events from the server via WebSocket are going into Seq and its API client in this version.

![image](https://cloud.githubusercontent.com/assets/342712/19752276/6aba07ba-9c3f-11e6-8d5a-b14960ebd8d5.png)

**Comment by nblumhardt** [comment]
@raybooysen the more I think about this one, the tougher it sounds to switch to WebSocket without compromising usability when there are a lot of events.

In the current model, where there is a short refresh interval, the events shown on-screen remain in stable positions for a couple of seconds between updates. I think readability will be compromised if these move in real-time, and in the case of events-per-second, the view will just be a blur. In the current scheme, the contents of the screen is amenable to skim-reading even if not all events can be read this way.

Combined with browser drawing perf and network usage considerations when there's a high rate of events, I think there's a substantial risk we'll just trade off one set of benefits/caveats, for another set of benefits/caveats, without really moving the UX forwards by making this change.

Thanks for raising this though, and I'm interested to know if I've missed anything that I should be considering here. Cheers!

**Comment by raybooysen** [comment]
Hi @nblumhardt 
Thanks for the update.

Depending on your mechanism for updating the UI, having live updates should be similar to tailing a log on a console, in that there shouldn't be blur.  At the moment I find readability on the UI hard because if there are a log of log entries, they suddenly jump instead of flowing naturally down the screen.

Would there be more network usage compared to the C# streaming API?

Thanks again for a great product, using it everyday

**Comment by nblumhardt** [comment]
Interesting feedback, thanks Ray.

Regarding network usage - yes, I think there would be more data transferred, at least without some tricky code to manage it. As it works currently, even if there are 1000 events/sec arriving, the UI will only receive one screenful per refresh interval, e.g. 50 events per 2 seconds.
