### ISSUE TITLE
Feature Request - Configure forwarder for multiple servers

### ISSUE THREAD

**Issue by wwwlicious** [datalust/seq-releases#425]
It would be useful to be able to configure a seq forwarder to use multiple forwarding locations based on  the log events. I guess what I am describing is a MQ on top of the db where each MQ can have it's own Seq endpoint.

**Comment by nblumhardt** [comment]
Thanks for the great suggestion, sorry it took a while to get back to you!

There are a few higher priority items currently for the forwarder (API key support in particular), while we work through them I think this ticket will be better tracked on UserVoice; I've moved it to: https://seq.uservoice.com/forums/268188-general/suggestions/16896361-route-events-from-seq-forwarder.
