### ISSUE TITLE
`any()`, `all()` as aggregate operators

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#427]
Let's say I am correlating events in my website by `RequestId`. I've had reports that ordering product `X` is flaky. The problem is, I have a lot of events tagged with `ProductId` equal to "X"` and a lot of events where `@Level` is `Error`, but they're not the same events.

What I want to find is the HTTP requests where _some event_ under the request is related to product `X`, and _some other event_ under the request is an error.

Here's how it should look:

```sql
select any(ProductId = 'X') as x, any(@Level = 'Error') as err
from stream
group by RequestId
having x and err
```

The result set gives me a list of `RequestId` values I can further interrogate (or, I can collect info by adding columns to the query above.

As with all non-trivial queries, people will probably need to refer to an example like the one above as a "recipe" - it's not obvious - but providing this would unlock a lot of scenarios that aren't accessible at all today.

**Comment by tsimbalar** [comment]
>  it's not obvious 

Indeed, I can't really wrap my head around this one :).

What is the return type of `any()` ? is it a boolean ? (i.e. equivalent to Linq's `.Any()`) . If the goal is to remain close to a _SQL-ish_ syntax, wouldn't that be called `EXISTS` ?

Just to be sure I get it, given this stream of events ...

Order | RequestId | Level | ProductId | Msg
------- | ------------- | --------| ----------- | ------
1        |  -               | ERR   | X             | unrelated
2        |  A              | INF     | X            | user 1 purchased X
3        |  A              | DBG  | X            | logged something about X
4        |  A              | DBG  | -            | http request success
5        |  B              | INF    | X            | user 2 is purchasing product X
6        |  C              | INF    | Y            | user 3 is purchasing product Y
7        |  C              | ERR  | Y            | exception while adding Y to cart
8        |  B              | ERR  | X            | exception while adding X to cart
9        |  B              | ERR  | -            | http request failure
10      |  D              | ERR  | -            | http request failure
11      |  E              | DBG   | -            | random request

this request (without `having`)
```sql
select any(ProductId = 'X') as x, any(@Level = 'Error') as err
from stream
group by RequestId
```

would return

RequestId | value of x | value of err
-------------|-----|----
null | false | true
A | true | false
B | true | true
C | false | true
D | false | true
E | false | false

and applying the `having` would give 

RequestId | value of x | value of err
-------------|-----|----
B | true | true


Is that correct ?

**Comment by nblumhardt** [comment]
Thanks for checking it out! Yes, your example is as I intend.

The SQL "standard" way would be to use subqueries and/or joins for this (so `EXISTS`/`SOME` etc.), but in this version the operators are closer to simple aggregates like `MIN()` over a group.

E.g. `MIN` accepts a stream of numbers, and returns the smallest. `ALL` in this proposal accepts a stream of Booleans and returns the logical conjunction.

I guess we're stretching what can be expressed without implementing subqueries and joins; I don't think they're going to make it in 3.2, so the question is probably whether we're prematurely claiming some logical/keyword territory that would be better saved for a full subqueries implementation...

I'm leaning towards finding names that make this usable in 3.2, since there's no way to express these kinds of queries otherwise. Interested to hear whether you think it's too far off the SQL path though (or if some naming tweaks are required)....

**Comment by nblumhardt** [comment]
Thinking the best way forward with this one is just to put it out there in a preview release and tinker. Will drop it into 3.2.12, due shortly :-)

**Comment by tsimbalar** [comment]
I did not get to play with it ... but anyway, as you mentioned that is pretty advanced for a very specific scenario. I guess it's good enough as long as there is an example somewhere to use as a reference :) 

Maybe a list of useful sample queries could be somewhere in the docs :)

**Comment by nblumhardt** [comment]
:+1: sounds good to me.
