### ISSUE TITLE
Feature Request: Autorefresh for SQL queries

### ISSUE THREAD

**Issue by qadmium** [datalust/seq-releases#428]
It would be useful to have autorefresh for SQL queries

**Comment by nblumhardt** [comment]
Thanks - yes :+1:

**Comment by nblumhardt** [comment]
@qadmium just thinking - does #438 cover the scenario you had in mind here?

**Comment by qadmium** [comment]
Yep, finally its exactly what I want

**Comment by nblumhardt** [comment]
Excellent :-)

Thanks very much for the reply.
