### ISSUE TITLE
Feature Request: Surface assignation events in the plugin API

### ISSUE THREAD

**Issue by dunkymole** [datalust/seq-releases#429]
If assignations were in the plugin API it would enable me to send and email/Slack to assignee, currently the dash isnt really part of people's workflow so it would be nice to draw their attention to something they ought to look at.

**Comment by nblumhardt** [comment]
Thanks again for posting this suggestion; I'm working through the backlog and think this one will need to be left for a future release. I've moved it to: https://seq.uservoice.com/forums/268188-general/suggestions/16896340-trigger-apps-when-events-are-assigned-to-a-user. Cheers!
