### ISSUE TITLE
Post-install, don't attempt to fall back to IE when the default browser fails to open

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#434]
On some systems, attempting to open the default browser fails. After installing Seq, when the user selects Browse Seq, we detect this issue if present and try opening IE directly instead. This no longer works on Win 10 - the file explorer opens instead :-) ... We should just give up and present an error, showing the desired URL.

**Comment by bendetat** [comment]
Don't know if this will help or not but on my machine (Windows 10 with Chrome as default), via LINQPad `Process.Start("http://localhost:5341")` works correctly. So does this in PowerShell;

```
start http://localhost:5341
```

I'm fairly sure this has worked on Windows since at least XP.

**Comment by nblumhardt** [comment]
Thanks Ben. Here's the Seq code:

```csharp
        public void Browse()
        {
            try
            {
                Process.Start(_listenUri);
            }
            catch (Exception)
            {
                Process.Start("explorer", _listenUri);
            }
        }
```

 I wonder if the problem is to do with `Seq.Administration.exe` running elevated?

**Comment by bendetat** [comment]
Running LINQPad elevated still worked:

```
[DllImport("shell32.dll")] public static extern bool IsUserAnAdmin();

void Main() 
{ 
	IsUserAnAdmin().Dump(); // true
	Process.Start("http://localhost:5341");
}
```

So I'm at a loss ;-)

**Comment by tsimbalar** [comment]
> `Process.Start("explorer", _listenUri);`

wait, but wasn't the process called "iexplore", and not "explorer" ??

**Comment by nblumhardt** [comment]
I would have thought so, but no, strangely.

```
C:\>iexplore https://getseq.net
'iexplore' is not recognized as an internal or external command,
operable program or batch file.
```

On this laptop (and on the earlier Win8 machine I think this was originally dev'd/tested on) `explorer` plays this role. Odd! :-)

**Comment by tsimbalar** [comment]
that makes absolutely no sense, bu ok :)

**Comment by nblumhardt** [comment]
Fixed; we'll now just show an error message if the URL launch fails.

**Comment by IanYates** [comment]
I've noticed Explorer.exe launching recently and have now just seen the new warning message instead on a 2008 R2 server that previously had Seq installed (I was updating over an earlier beta release).  Weird, since `Windows+R` ->  `http://localhost:5341`   works just fine and launched IE 11.  No biggie but still a bit strange.

**Comment by IanYates** [comment]
And for iexplore I've always just gone to `c:\Program Files\Internet Explorer\iexplore.exe`.  We have some batch files force load from there (reasons...) even when the user's default browser is Chrome.

I don't have Win 10 on my laptop - laziness more than being a luddite - so maybe the Internet Explorer folder isn't present anymore?

**Comment by nblumhardt** [comment]
@IanYates thank you for the info. I just went back to this code and found #477, which was being masked by the original catch-all handler.

Writing some release notes for 3.3 right now, will have a small update with some minor issues like this one fixed later in the week. Cheers! :-)
