### ISSUE TITLE
Ingestion-only port

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#437]
When Seq is on an internal network, and applications in a DMZ or similar, allow an exposed port to be designated the "ingestion port" and reject all non-ingestion requests on that port.

**Comment by nblumhardt** [comment]
Initially this would be a config-only option, like:

```json
  },
  "api": {
    "listenUris": [
      "http://localhost:5341/",
      "http://my-seq/prd"
    ],
    "ingestionPort": 5341
  },
```

In this case, only `/api/events/raw` would be available on the `5341` port, with the web UI exposed on `80`.

**Comment by cbdabner** [comment]
Thanks @nblumhardt that looks good.

I think the Seq Forwarder could provide some pretty flexible options in future once it supports passing through API keys etc.
