### ISSUE TITLE
Dashboarding

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#438]
* Any numeric timeseries query - `count()`, `max()`, `percentile()` - can appear on the dashboard
 * Multiple per-user as well as shared dashboards
 * More configurable visualization - lines/bars/points/counters in the first cut
 * Variable refresh rates (manual, 10s, 1hr and so-on)
 * Deep-linkable to a specific dashboard, time range, and refresh rate for use on overhead dashboards
 * Dashboard cloning, JSON import/export
 * Click-through to open a chart as an interactive query
 * Drill-through from a point as a selection of events contributing to the point value

**Comment by nblumhardt** [comment]
Just a note, with the amount of completed (and soon-to-be completed) work in 3.3 it's possible this item will move to 3.4 so that we can get improvements like the SQL query editor and compact JSON support into customers' hands faster.

**Comment by nblumhardt** [comment]
The _dash_ is dead; long live _dashboards_ ;-)

![image](https://cloud.githubusercontent.com/assets/342712/23112143/9296d476-f779-11e6-93ac-441409e7a45f.png)

**Comment by nblumhardt** [comment]
Still a lot of detail work to go (and gaps to fill), but overall this is coming together nicely!

![image](https://cloud.githubusercontent.com/assets/342712/23484467/d573e170-ff22-11e6-9297-81644d6d2aac.png)

**Comment by ChrisSimmons** [comment]
Looks fantastic, Nick!

**Comment by BlairPaine** [comment]
This looks really good @nblumhardt

I'd love to be able to build a dynamic dashboard which provides heath checks for executing processes.  Will it also be possible to create a dashboard which accepts events based on select criteria but also displays multiple heartbeat lines on a graph based on a certain property?

For example, I have a module.  I want any executions of that module to report to SEQ every 5 minutes by sending a defined message. However, there could be multiple instances of that module running at the same time. Each instance would have a unique GUID property to uniquely identify it and that property is sent with any message from that instance.  I would want one heartbeat shown per instance/GUID.  I won't know ahead of time what the GUID will be or how many executions will be running.

Together with the dead-mans-switch scenario provided in the upcoming alerting feature I could then create dashboards to monitor each execution individually (and messages from those executions) created by our administrators.

Perhaps in the future you could create dashboard templates and then you can have multiple dashboard instances created automatically when a certain type of event is received.

Cheers,
Blair.

**Comment by andymac4182** [comment]
@BlairPaine Would I be right in thinking you could `Group by` the property that includes the GUID property you are providing. I am doing this in our dev environment to show number of errors per application where `ApplicationName` is in the `Group by`?

**Comment by BlairPaine** [comment]
Thanks @andymac4182 I'll give that a try and see how it looks.

**Comment by nblumhardt** [comment]
@BlairPaine great to hear you're checking it out! @andymac4182's suggestion is the one I'd offer - keen to hear how it comes together for you 👍

**Comment by nblumhardt** [comment]
The planned "4.0" functionality for this feature is done! Testing a new preview build that will be published before moving on to #537 and the other remaining items in the 4.0-pre milestone.
