### ISSUE TITLE
Assignments not loading on dashboard

### ISSUE THREAD

**Issue by chriswithpants** [datalust/seq-releases#448]
I was assigned a task but the assignments section of the dashboard will not load.

Seq version 3.2.16 running in Azure Classic VM

Screenshot:
![image](https://cloud.githubusercontent.com/assets/2295352/17088069/63889ae4-5255-11e6-8f5d-3336d6b743c3.png)

Logs attached.
[seq-20160725.zip](https://github.com/datalust/seq-releases/files/380629/seq-20160725.zip)

**Comment by nblumhardt** [comment]
Thank you Chris, reproduced and fixed on master. The next 3.3 preview build will include this, currently aiming for late this week.

**Comment by chriswithpants** [comment]
You da man.
