### ISSUE TITLE
Enable autorefresh via URL parameter

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#452]
When opening Seq as a tab on a web-based dashboard, accept `autorefresh=true` to turn on auto-refresh without manual intervention.

Via: http://docs.getseq.net/v3/discuss/579955fea7f817170056f5ef

**Comment by centur** [comment]
Can I suggest to use same consistent approach with `deletion=enabled`
so it'll be either `autorefresh=enabled` or allow us to do `deletion=true`.

It's really helps when tokens and values are named in the same way across features.

**Comment by markledwich2** [comment]
I'm looking for this too. I open seq when executed from vs code for a variety of long running tasks (filtered to events from that task). Works well except i always have to click auto-refresh every time.

**Comment by nblumhardt** [comment]
Thanks for the feedback. We'll try to get this in with 4.0.

**Comment by smudge202** [comment]
Only just read your comment on my blog. Quick message here as a little reminder. 😄

**Comment by nblumhardt** [comment]
Unfortunately this one's going to miss out on 4.0, which needs to close and stabilize. Moving to 4.1 so it's not lost :-)

**Comment by nblumhardt** [comment]
```
&autorefresh
```

will do it.

(The other Boolean parameters now use similar names - `&deletionEnabled`, `&showExpanded`, though the old URIs with `&deletion=enabled` and `&show=expanded` are supported for backwards-compatibility.)
