### ISSUE TITLE
Pass ApiKey and MinLoggingLevel from Seq Sink through SeqForwarder

### ISSUE THREAD

**Issue by morrisnc** [datalust/seq-releases#475]
I have been testing the use of SeqForwarder and find the idea very useful.  However I was using the ApiKey on Seq Server to add enriched values such as Environment and Application name plus control the Minimum Logging Level dynamically.  Both of these feature seem to disappear when using the SeqForwarder.  These are extremely desirable features that I would request to be added to SeqForwarder.

Ed

**Comment by nblumhardt** [comment]
Thank you for the note, Ed. Good to hear that the forwarder is heading in the right direction.

There's a ticket tracking this in the forwarder repository here: https://github.com/datalust/seq-forwarder/issues/2 - I'll leave this issue open here as a pointer to it :+1: 

Thanks again!
Nick

**Comment by nblumhardt** [comment]
Just a quick progress update - there's an early cut of this feature in the MSI linked from the https://github.com/datalust/seq-forwarder/issues/2 issue - all feedback appreciated.

**Comment by nblumhardt** [comment]
Done and published - you can grab the latest MSI from: https://github.com/datalust/seq-forwarder/releases
