### ISSUE TITLE
Ingested data requiring BigInteger storage does not round trip through serialization

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#479]
If an incoming value exceeds the storage of `decimal` it is stored correctly, but on deserialization (e.g. when re-loading events from disk) an `InvalidCastException` is raised.

**Comment by nblumhardt** [comment]
As of this fix, Seq will not handle queries against `BigInteger` values, but will not have other problems handling them (they'll be converted internally into strings).

**Comment by chosenbreed37** [comment]
Thanks for the fix.
