### ISSUE TITLE
Seq.App access current app instance title

### ISSUE THREAD

**Issue by jansson** [datalust/seq-releases#484]
I thought I had already requested this before but couldn't find the issue, so forgive me if this is a duplicate.

When writing apps, it'd be great if we could gain access to the current app instance's title.

**Comment by nblumhardt** [comment]
Thanks Kristoffer, I have some recollection of you raising it too, but I'll leave this ticket open until I find the old one. I should have a chance to take a shot at this one shortly.

**Comment by nblumhardt** [comment]
Done! The properties are `App.Id` (the app instance id) and `App.Title` (the configured app instance title). The _Seq.Apps_ package will be updated when 3.4 becomes available.
