### ISSUE TITLE
Auto-refesh + FromNow

### ISSUE THREAD

**Issue by dunkymole** [datalust/seq-releases#489]
Often times I have a standing query running with Auto-Refresh enabled. I might try an action which triggers logging from all over a distributed system. I can then turn off Auto-Refresh and inspect what happened at leisure. The next thing I probably want to do is clear down the log view and do a variant of the action and repeat the process. It would be great if I could either:
- Have a shortcut to select 'now' as the FROM time. After which I could turn Auto-Refresh on
- Have an an option to do both together - Auto-Refresh from Now.

**Comment by nblumhardt** [comment]
+1 for the "Now" shortcut. I think "Auto-refresh from now" is also interesting, but fitting a "Now" option into the datepicker seems like a good first step. Thanks for the suggestion!

**Comment by nblumhardt** [comment]
![dateselectnow](https://cloud.githubusercontent.com/assets/342712/19880552/08de4ec0-a04a-11e6-80f3-6e7fa9a124c6.gif)

**Comment by dunkymole** [comment]
Winner. Thanks. :thumbsup:
