### ISSUE TITLE
CSV export gives strange output for the `Properties` column

### ISSUE THREAD

**Issue by adamchester** [datalust/seq-releases#492]
Seq v3.3.20
Using the following query:
```sql
select ToIsoString(@Timestamp) as Timestamp,  @Level,
       ToHexString(@EventType) as EventType,  @Message, @Exception, @Properties
from stream
order by Timestamp desc
limit 100
```

I can see the `@Properties` rendered in the Seq event web view output table, however when I export to CSV, the `@Properties` column shows data like this:
![image](https://cloud.githubusercontent.com/assets/570470/18576584/3d4dc746-7c26-11e6-83d2-8c30b096082a.png)

**Comment by nblumhardt** [comment]
Ah, that's an annoying one to have slipped through. Thanks for the report! Will ship this in a new patch to 3.3.

**Comment by nblumhardt** [comment]
3.3.23 is up now :+1:
