### ISSUE TITLE
Delete Policy list sort order is a bit quirky.

### ISSUE THREAD

**Issue by centur** [datalust/seq-releases#493]
Very minor bug - sort order on Delete policy list doesn't take in account timespan of the policy just a first number - so looks a bit weird. See attached screenshot

![image](https://cloud.githubusercontent.com/assets/720822/18693768/ba41639c-7fe7-11e6-8eb0-5db8ef478e14.png)

**Comment by nblumhardt** [comment]
Agreed :-) thanks for the note.
