### ISSUE TITLE
long numbers are treated as integers in messages

### ISSUE THREAD

**Issue by DarkWalker** [datalust/seq-releases#498]
Lets post two messages:
```
{
  "Events": [{
    "Timestamp": "2016-10-14T10:45:08.12345+03:00",
    "Level": "Warning",
    "MessageTemplate": "Id =  {Id}",
    "Properties": {
      "Id": 4060741400040636189
    }
  }]
}
```

and 
```
{
  "Events": [{
    "Timestamp": "2016-10-14T10:45:08.12345+03:00",
    "Level": "Warning",
    "MessageTemplate": "Id =  {Id}",
    "Properties": {
      "Id": "4060741400040636189"
    }
  }]
}
```
please note that in the first message Id property is a number and in the second - a string. I expect that both of these messages to look the same, but they look different: 
![id](https://cloud.githubusercontent.com/assets/1113773/19379736/2ba2873e-91fc-11e6-9394-cef38d36f583.png)

When you download "Raw json" for the number you get the correct result:

```
{
    "@t": "2016-10-14T07:45:08.1234500Z",
    "@mt": "Id =  {Id}",
    "@m": "Id =  4060741400040636189",
    "@i": "0616bd81",
    "@l": "Warning",
    "Id": 4060741400040636189.0
}
```
But it looks like Seq does not display the "@m" part of this, but tries to use "@mt@ and properties to construct the message and fails to do so correctly.

I am using Seq 3.3.20

**Comment by nblumhardt** [comment]
Thank you for the report. This is due to JSON deserialization of the properties into JavaScript numbers, which are 64-bit floating point and don't have enough precision to display the full string of digits. #216 is the issue tracking this. Thanks!
