### ISSUE TITLE
Feature request: Provide "Description" or "Notes" on each API Key

### ISSUE THREAD

**Issue by ChrisSimmons** [datalust/seq-releases#499]
It would be valuable to have a free-text field for "Notes" or "Description" on each API key (up to some reasonable length limit of course).  This would be good for descriptive text on the API key "owner", application purpose, contact information, or any other notes.  As of now, the title can be used for a decent amount of info, but the title is better as a title.

**Comment by ChrisSimmons** [comment]
I suppose, since keys are not able to be regenerated in place, this might not be as simple as I thought.  i.e. if you have a lot of information recorded on an API key, then you wouldn't want to have to copy all that info over to another key when the key needed to be regenerated.

**Comment by nblumhardt** [comment]
Thanks for the suggestion Chris! Will give this some thought. "Regenerate" is also worth considering, I think 👍

**Comment by nblumhardt** [comment]
Hi Chris - just taming the issue tracker, I've moved this to our UserVoice site at https://seq.uservoice.com/forums/268188-general/suggestions/16895836-provide-description-or-notes-on-each-api-key. Cheers!
