### ISSUE TITLE
Sql-syntax Query : group by substring

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-releases#501]
I am trying to extract some statistics about some batch job that we are running, based on the information stored in Seq. 

Basically I would want to count events based on the beginning of the string value of a property.

For instance, with events (text in bold represents the template placeholders): 
- Error while processing **GET** **/api/v1/foo/bar**
- Error while processing **POST** **/api/v1/baz/qux**

**How could I get the number of errors grouped by API endpoint (`/api/v1/foo` or `api/v1/baz` ) ?**

I've seen the ["built-in functions"](http://docs.getseq.net/docs/built-in-properties-and-functions) like `StartsWith` , `Contains` , `IndexOf`, and those can help with filtering, but they only return booleans.

I guess in my case, I would need some sort of `Substring(startIndex, length)` function and use it in the `GROUP BY` clause (and maybe mix it with a bit of `IndexOf` in some cases)... 

Would that make sense ? and if it does, I guess this is a feature request :)

**Comment by nblumhardt** [comment]
Thanks for the note. There isn't a facility for this currently, but it should be feasible to implement. I think some `CASE`-type logic would be required too; something for us to flesh out.

I don't suppose you have any opportunity to log the verb and endpoint as separate properties at the source? That would make this trivial :-)

**Comment by tsimbalar** [comment]
Oh, sorry, it was not clear in my example ... the **HTTP verb and URI are actually separate properties** (it shows when looking at the markdown source :P) ... So my request is really about the beginning of the URIs. so if it's trivial, then I'm all ears :)

**Comment by nblumhardt** [comment]
Ah, I see - thanks for the clarification 👍

**Comment by nblumhardt** [comment]
`Substring(Endpoint, 0, 11)` will do this in 3.4.

The third parameter, `length`, may be omitted by substitution of `null`, to mean "to the end":

```csharp
Substring(AValue, 5, null)
```

**Comment by Suchiman** [comment]
Awesome new feature!
I'm testing 3.4.7-pre and i'm not sure if it's a bug or unintuitive behavior but when you specify `length` to be larger than the input is, `Substring` will return null rather than to the end which i would have expected.
E.g. 
```sql
SELECT Substring('test', 1, 100) AS text
```
yields `null`

While
```sql
SELECT Substring('test', 1, 3) AS text
```
yields `est`

**Comment by nblumhardt** [comment]
Thanks for the feedback @Suchiman. It's by design, matching the behaviour of `string.Substring()` in C# (which throws when `length` is past the end), but your comment made me realize that this is in conflict with TSQL's `Substring`, which behaves as you expect. I'll change it 👍

**Comment by nblumhardt** [comment]
Done.
