### ISSUE TITLE
Newtonsoft.Json.JsonReaderException: Input string '7.6813420232243128E+31' is not a valid decimal.

### ISSUE THREAD

**Issue by 80dB** [datalust/seq-releases#509]
Sometimes when filtering we get this error.

See the attached stacktrace:
[stacktrace.txt](https://github.com/datalust/seq-releases/files/585942/stacktrace.txt)

Note that we have a custom application which submits logs to Seq. Also it gets so much logging that finding out the log message that causes this is near impossible.

**Comment by nblumhardt** [comment]
Thanks for the report. I think this is a duplicate of #496.

**Comment by 80dB** [comment]
You are right, most likely the same issue. Close this one :)

**Comment by nblumhardt** [comment]
Thanks :+1:
