### ISSUE TITLE
Add a way to quickly clear an entire Seq database

### ISSUE THREAD

**Issue by 80dB** [datalust/seq-releases#510]
We had a few instances where the Seq database filled up quickly due to a bug in an application. Deleting the extends helped but an easy way to clear the entire database would be nice.

**Comment by nblumhardt** [comment]
Thanks for the suggestion.

**Comment by laurencee** [comment]
This would be pretty useful for me as well as often when I start new projects I'll end up with a lot of unneeded log messages which I just throw away as I get the app closer to a release state.

Usually it's a case of leaving the service/site on overnight or a weekend and then come back to a heap of useless log messages, at that point it's much easier to just wipe it all out.

**Comment by nblumhardt** [comment]
Would a command-line command (`seq truncate` or similar) be an improvement on this, or are you thinking of through-the-UI functionality?

**Comment by laurencee** [comment]
I was thinking through the UI, obviously it'd need some guard to prevent people mistakenly clicking it if there was a UI element for it. Maybe making someone type out "TRUNCATE" in an entry box or whatever, people tend to ignore yes/no prompts too often these days heh.

I'm usually running the Seq instance on some remote machine and just interact with it through the web interface so the command line option wouldn't be particularly useful for me personally.

**Comment by nblumhardt** [comment]
Just doing some issue tracker maintenance - this is an interesting idea, but since it can be achieved efficiently via the file system, I don't think this one is going to make the cut in the near future. Closing for now, maybe one to reconsider down the track. Thanks for the suggestion and feedback, @80dB and @laurencee!
