### ISSUE TITLE
How can I add a subproperty as tag

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-releases#518]
Some of my messages contain properties of complex type ...

For instance : 
```
Row = {RowIdentifier="foo", FileName="toto.csv}
```

I would like to add Row.RowIdentifier as a tag in the event stream.

The UI only lets me pick one of the "root" properties, so I tried "editing the signal as JSON" , and added a tag like so :
```
  "TaggedProperties": [
    {
      "PropertyName": "Row.RowIdentifier"
    },
...]}
```
but this does not seem to work.

I also tried 
```
  "TaggedProperties": [
    {
      "PropertyName": "Row[\"RowIdentifier\"]"
    },
...]}
```
but it does not work either.

Is there a way to show a "subproperty" as a tag ? is it supported ? 

Thanks in advance !

PS : Seq is saving our life again this week, to extract some statistics of a massive import job we are running these days

**Comment by nblumhardt** [comment]
Hi Thibaud,

This isn't possible at the moment, though just a couple of weeks ago this UserVoice item was raised to track it:

https://seq.uservoice.com/forums/268188-general/suggestions/17190632-tags-from-complex-property-values

I'll close this ticket as it's a duplicate, but will keep the feature in mind. Thanks!
