### ISSUE TITLE
Button to "pin" a long sql query is unclickable

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-releases#523]
This has been driving me nuts for 5 minutes :)

When writing a SQL query that is a bit long , the "pin" icon in the "history of last queries" becomes unclickable, making it impossible for the user to save it for later ... 

![image](https://cloud.githubusercontent.com/assets/160544/21306497/909deeae-c5d1-11e6-8c68-797ad38abcf6.png)

I believe this appear when the "ellipsis" is showing. Hacking the css with Firefox Developer Tools to change the rule

`.filter-bar .content .inset-controls .history ul.dropdown-menu li` to make `max-width` bigger fixes it (i.e. if big enough to make the *ellipsis* disappear)

*As of Seq v3.4.18 with Firefox 50.1.0*

**Comment by nblumhardt** [comment]
Thanks Thibaud - this seems like a regression, I'm now seeing the same behaviour in Chrome also 👍
