### ISSUE TITLE
CSV timestamps in local time zone

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#531]
When query results are exported to CSV, ISO 8601 timestamps in UTC are used. This is great for programming language clients, but not so good for use in Excel (which has unbelievably poor ISO format and time zone handling).

Some mechanism for exporting results in plain local time would be useful.

**Comment by nblumhardt** [comment]
This one would be great to address down the line, but looking at priorities in the current issue list, it doesn't appear we'll be able to take this one on in the near future. Closing, but feedback/suggestions most welcome.

**Comment by toorani** [comment]
We need to have the time in local time zone in CSV file out but there isn't any way to get that.
It could be useful if you would up its priority.
