### ISSUE TITLE
Backups from freshly restored server are not decryptable with the server key ? 

### ISSUE THREAD

**Issue by centur** [datalust/seq-releases#534]
Hi, it seems like there is some issue with encryption of backups on the new server that is restored from backup. It's easier to explain with some illustration, e.g. we have an initial server:
`Adam` with `AdamKey`, Adam has a policy to backup it's config every day. 

So when we've built another server `Bob` to take off some load from `Adam` and restored `Bob`'s configuration from Adam backup using AdamKey - everything was fine. Because it was restored from Adam - we have same config backup policy enabled, so Bob is automatically backing configuration up with `BobKey`

Now we've built another server, `Cory` and when I tried to restore it from Bob's backup with a correct `BobKey` - restoration failed with an error `Could not create backup: Padding is invalid and cannot be removed.`. I tried this 3 times and verified that the key is exactly Bob's (`seq show-key`).

This message actually indicates that the key is incorrect or backup can't be decrypted (which may be a good indication that it needs to be improved or extra clarifications added there ;) )

Restoration of Adam backup with Adam key on Cory server is working without any problems.

I suspect that the server Bob, after it was restored from backup, somehow uses the different backup encryption key, not the one it displays with `seq show-key`. So there might be a similar problem with Cory's backups. I can check after it'll create few backups automatically.

**Comment by nblumhardt** [comment]
Hi Alexey, thanks for the note.

When `Adam` was restored onto `Bob`, the master key for `Bob` would have changed to `AdamKey`. Backups written by `Bob` after the restore should be restorable with `AdamKey`. However, `show-key` on `Bob` should show this key correctly.

One thing to check - are you specifying `--storage` or `--name` when requesting the key from `Bob` using `seq show-key`? If a custom storage path or instance name is being used, you'll need to specify this.

Does that trigger any ideas?

Cheers,
Nick

**Comment by centur** [comment]
Yes, it does... I wasn't using `--storage` when retrieving key, but all our instances are in custom storage. I've just re-tested with proper storage key - Bob shows the same key as Adam. So this is my mistake - I retrieved an incorrect key.

Side note - this is not very intuitive that having a single but custom SEQ instance per VM demands to have `--storage` for all commands. Can't it just check the services and identify that there is only once instance of SEQ there and it can use it's `--storage` and `--name` as defaults for all invocations if these params were not explicitly specified ?

**Comment by nblumhardt** [comment]
Thanks for the follow-up, glad to hear it's sorted out.

Agreed regarding the need to specify `--storage`, it's already been improved for Seq 4.x in #524. In the new version, you still would need to specify `--name` or `-n` for named instances, but for both kinds the `--storage` parameter will be inferred correctly, so long as the instance is installed as a Windows service.

Thanks for all the feedback!
