### ISSUE TITLE
New dashboarding doesn't work in IE / Edge

### ISSUE THREAD

**Issue by Suchiman** [datalust/seq-releases#538]
It fooled me for half an hour but then i've realized, its just not working in IE or Edge.
If you look at it in IE11 or Edge, it will look like this
![iexplore_2017-03-14_17-14-17](https://cloud.githubusercontent.com/assets/7110884/23910369/c132b2ca-08d9-11e7-8ebd-85079329e180.png)
Theres no error printed on the console.
In Firefox and Chrome it works and displays it as expected
![chrome_2017-03-14_17-17-16](https://cloud.githubusercontent.com/assets/7110884/23910461/15a22156-08da-11e7-8d40-cdd4306ea830.png)

**Comment by nblumhardt** [comment]
Ick, thank you @Suchiman. I should have added the disclaimer "tested in Chrome and FireFox" ;-)

I'll patch this up and get IE11/Edge shored up in the next build.

(Part of #438 )

**Comment by nblumhardt** [comment]
Issue was a `new Date(str)` which assumed `str` was ISO-8601, but wasn't. Thanks again for the report!
