### ISSUE TITLE
Option to redirect HTTP traffic to HTTPS

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#541]
When Seq is configured to listen on an HTTPS URL, provide an option to redirect HTTP traffic to it.

**Comment by andymac4182** [comment]
It would be great if this could include 80 and 5341.

**Comment by nblumhardt** [comment]
Implemented via:

```
seq config -k api.redirectHttpToHttps -v true
```

The implementation is simple, in that it will simply redirect to https/443 for the same hostname as the originating request, irrespective of what URIs Seq is listening on.

Unfortunately, there doesn't seem to be a way to get HttpClient in .NET to follow redirects carrying the POST body (redirected POST requests end up as GETs), so ingestion traffic is ignored.

We might be able to get _Serilog.Sinks.Seq_ to implement the redirection process manually, through a custom `HttpMessageHandler`; if so, ingestion redirects could be turned on in the future.
