### ISSUE TITLE
Suggest addition to documentation, to clarify the reasons why running under local system account is not recommended.

### ISSUE THREAD

**Issue by AndrewSav** [datalust/seq-releases#543]
I think the documentation can be improved by warning the user that if they leave Seq running as Local System, all plugins are also running as Local System, and thus, can do anything. Given that plugins are installed from partially trusted (or untrusted) nuget feed this may convince people to take the warning more seriously than they would otherwise.

http://docs.getseq.net/docs/production-deployment

**Comment by nblumhardt** [comment]
Thanks for the suggestion, Andrew. The whole service account/LocalSystem thing is quite subtle, I'm not sure about trying to explore the topic in more depth, since the issue is pretty well-covered elsewhere. I'll give the docs some thought though. Cheers!

**Comment by AndrewSav** [comment]
A link to where ever it's explored from the docs could help a customer to reach that decision.

I understand that there may be a fine line here between giving your customers impression that your product is insecure and adequately informing them of relevant security precautions. (After all, an admin on Seq can pwn the whole server with everything on it with the default installation settings).

Your certainly do not want to make your product appear insecure / unsafe, I get that. In this respect an explicit recommendation to use a different account that you currently give is golden -  if someones server gets pwned, you tell them - you did not follow our recommended settings that are clearly given in the official documentation.

At the same time I felt that you could be more helpful to your customers, so that they do not end up in this position in the first place. The topic is sensitive, so I felt you might consider that a bit more persuasion in the docs is not uncalled for.

I however agree that this is quite subtle, so I just wanted to put this on the table in case you'd like to consider it. Thank you for your attention.
