### ISSUE TITLE
API key editing: don't require pressing "Add" before properties are attached

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#548]
From: http://docs.getseq.net/v3/discuss/58ec859e893a732500dc3176

**Comment by KodrAus** [comment]
![capture-unsaved-props](https://user-images.githubusercontent.com/6721458/32764257-542c244e-c950-11e7-8a2e-fa91351ef7a7.gif)

We've fixed up this little papercut when adding or editing API keys. Now if you enter a new property, but forget to tap the _ADD_ button, we'll go ahead and add the property before saving the key.

**Comment by tsimbalar** [comment]
Well that's some pretty quick on-boarding ;)
Welcome @KodrAus  :)
