### ISSUE TITLE
Disk I/O error (-1022) in internal diagnostic log

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#549]
We've received a few Seq diagnostic log files in the last month reporting disk I/O errors during compaction, like:

```
2017-04-01 01:23:45.678 -07:00 [Error] Unable to compact extent "9/21/2016"
Seq.SeqException: Defragmentation of 9/21/2016 failed; ESENTUTL returned -1022
   at Seq.Storage.Events.Extents.Extent.Compact(Boolean full)
   at Seq.Storage.Events.Extents.Extent.TryCompact(Boolean full)
   at Seq.Storage.Events.ExtentCompactor.Compact(ExtentMap extents, CancellationToken cancel)
```

This is normally reported after a background call to `ESENTUTL.exe`, and once the error is reported for one extent, it often reappears in later extents. The extents themselves are otherwise loaded and queried by Seq without problems, but other intermittent issues have been reported in conjunction with this error occurring.

Error -1022 is a general disk I/O error that is expected to indicate disk trouble. One of the recent cases confirmed there had been other apparent hardware-related issues in the Windows event log, so there's probably very little we can do in those cases. Since masses of data are written through Seq each day on thousands of machines running all kinds of hardware, some disk problems are inevitable.

I'm raising this ticket for three reasons though:

 * To collect data, in case the recent cluster of reports indicates some reason for increased risk,
 * To investigate how Seq could better handle this situation internally, and
 * To track some actions we're taking pre-emptively, such as upgrading the version of _Esent.Interop.dll_ we're shipping with Seq 4 (we'll be moving [from 1.9.1.0 to 1.9.4](https://managedesent.codeplex.com/releases))

**Comment by danpowell88** [comment]
We are seeing this issue on an entirely virtualised server and logging drive (vmdk san drive) that as far as we can tell is highly unlikely to have disk issues.

It is also stopping truncating from happening.

Running version 3.3.23

**Comment by nblumhardt** [comment]
Thanks for the info @danpowell88. Is there any chance you can update to a patch build that includes the later _Esent.Interop.dll_? This isn't published on the downloads page as the changes are being rolled into the upcoming 4.0 release. If you can shoot me a mail at support@getseq.net, I'll send details through. A zipped copy of the internal Seq logs would also be a great help. Thanks again!

**Comment by nblumhardt** [comment]
We haven't had any further reports of this appearing post 4.0; I'll close this but will reopen if we obtain any more information.

**Comment by wwwlicious** [comment]
Hi @nblumhardt,

I am seeing this appearing in the diagnostic logs running 4.2.605.
The server is virtualised using vmware esx datacentre and storage runs on a SAN.
This looks to be preventing truncation also.
I will forward on the logfile to the support address for you.

**Comment by nblumhardt** [comment]
Thanks for sending that through, @wwwlicious.

I'll take a look at the diagnostic logs shortly, however if it's convenient you can try a repair using:

```
seq stop
seq compact --repair
seq start
```

This can take a little while to run, but generally resolves this problem reliably. Let me know if you give it a shot, and whether you have some success via that route.

Best regards,
Nick

**Comment by wwwlicious** [comment]
@nblumhardt Thanks, that seems to have resolved things.
