### ISSUE TITLE
Provide a way to track events ingested without an API key

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#551]
It's difficult to move from no API key use to full/required API key use, because there's no easy way to tell whether events arrived without a valid API key. ([Discussion](http://docs.getseq.net/v3/discuss/58f00695486baa0f0020ad41).)

To address this we'll:

 * Create a special API key _None_, that will be used when events are accepted without a valid API key
 * Log invalid API keys to the Ingestion Log

This way, the rate counter and attached properties on _None_ can indicate whether events are arriving without valid API keys, and which ones they are.

When API keys are required for writing events, the _None_ key will disappear.

**Comment by nblumhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/342712/25031120/de9d6480-210d-11e7-9f50-80966950e3ad.png)

**Comment by nblumhardt** [comment]
```
2017-04-14 12:39:22 Payload from "::1" specified invalid API key "xyz"
```

**Comment by nblumhardt** [comment]
This was a worthwhile exercise - found an opportunity to create many fewer document store sessions during ingestion, hopefully that will translate to a small performance improvement as a side-effect.

**Comment by tsimbalar** [comment]
Nice ! seems like a good complement/workflow for #367 ! 

This way I can just : 
- set an arbitrary api key in my applications' config files
- check out the ingestion log to see if I any of my apps is not "officially registered" in Seq
- add the api key in Seq
