### ISSUE TITLE
View and remove permalinks

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#559]
Seq's various event bookmarking features create "permalinks" behind the scenes that exclude events from retention policies that would otherwise remove them.

In 4.0, the Pins/Assignments/Permalinks features will all merge into a single "Permalink" concept.

The _Preferences > Permalinks_ screen will show a user their list of permalinked events, and allow permalinks to be removed.

**Comment by nblumhardt** [comment]
![image](https://cloud.githubusercontent.com/assets/342712/25569228/4d4f66b2-2e56-11e7-8859-807d6be76504.png)

**Comment by andymac4182** [comment]
Is there a way to get this for all users? Like in the case of an employee leaving that has permalinks saved?

**Comment by nblumhardt** [comment]
@andymac4182 not in 4.0 as it stands, but this could be a future enhancement 👍

For now, clearing out events using _Retention_ > _Manually delete events_ will do it (albeit un-gracefully).
