### ISSUE TITLE
When timestamps are shown in UTC, calendar/date pickers should also use UTC

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#561]
#399 allows event timestamps to be viewed in UTC. However, the two From/To date picker controls remain in the user's local time zone. It seems that these also should switch to UTC if this option is enabled.

**Comment by nblumhardt** [comment]
@HakanL is this behavior you would expect? Thanks!

**Comment by HakanL** [comment]
Yes, I think that makes sense.

**Comment by nblumhardt** [comment]
Done! The calendars/datepickers and timeline control will now render in UTC when the option is set.
