### ISSUE TITLE
Query indexof as label not allowing where filtering

### ISSUE THREAD

**Issue by laurencee** [datalust/seq-releases#575]
**Seq version: 4.0.58**

Given the following query returns some results:
```
select IndexOf(@Message, /(\d)+ms/) as index
from stream
limit 1024
```

If you try to apply a `where` statement to the index label, the query no longer returns results

```
select IndexOf(@Message, /(\d)+ms/) as index
from stream
where index > 0
limit 1024
```

**Comment by laurencee** [comment]
If I change the where to
```where index is null```
then it returns all the results again so I guess the label isn't being set to the value of the select statement?

**Comment by nblumhardt** [comment]
Thanks for the report, Laurence. Yes, I think you're right. I get results with:

```sql
select IndexOf(@Message, /(\d)+ms/) as index
from stream
where IndexOf(@Message, /(\d)+ms/) > 0
limit 1024
```

I don't think `select` column labels are being bound in `where` clauses (the test cases we have are all for `having`).

The workaround should help for now, but I think the behavior you're expecting is what Seq should do here.

**Comment by nblumhardt** [comment]
Changing this to 'enhancement', since the current behavior is consistent with standard SQL.

**Comment by nblumhardt** [comment]
![image](https://user-images.githubusercontent.com/342712/27319364-62c69c90-55d4-11e7-8408-8df4d33cfe04.png)
