### ISSUE TITLE
Dashboard regular expression flickering error

### ISSUE THREAD

**Issue by laurencee** [datalust/seq-releases#577]
**Seq version: 4.0.58**

I've setup the following query:
```
select mean(ToNumber(SubString(@Message, IndexOf(@Message, /(\d)+ms/), ((length(@Message)) - (IndexOf(@Message, /(\d)+ms/))) - 2))) as AUDDelay
from stream 
where @Message like 'Average%delay%ms'
group by time(1m)
limit 10000
```

Every so often the dashboard item will flicker with a parsing error for the query.
```
The query could not be executed. 
Syntax error (line 1, column 62): unexpected `\`.`
```

Then on the next refresh it's generally back to normal.

![image](https://cloud.githubusercontent.com/assets/3850553/26658204/e51c86ba-46ab-11e7-98a7-669686fe81ad.png)

**Comment by nblumhardt** [comment]
Thanks for the report, this is an odd one! Does the error reappear even if you refresh the dashboard using the browser's refresh button?

If you're able to open the browser developer tools and find the failed network request corresponding to the chart loading, could you possibly collect the _request URL_ and include it here, or mail it to me via support@getseq.net?

Thanks again!

**Comment by laurencee** [comment]
Sure I'll send you a mail with the details.

**Comment by nblumhardt** [comment]
@laurencee just thinking about this one, does it appear from multiple client machines, or just the one? (I'm still suspecting there might be some kind of response caching going on, somewhere.)

**Comment by laurencee** [comment]
It appears from multiple client machines.

**Comment by nblumhardt** [comment]
Just a quick note - I reproduced this twice on a test machine. Unfortunately, I've now been running for hours with an appropriate breakpoint set, but no repro :-) ... Will keep at it.

**Comment by nblumhardt** [comment]
Found! First threading issue in _quite_ a while :-)

The code assumed that instances of `Tokenizer<T>` from https://github.com/datalust/superpower are safe for concurrent access, which is incorrect: https://github.com/datalust/superpower/blob/dev/src/Superpower/Tokenizer%601.cs#L78

The `Previous` property is used to decide whether a token is a division operator or regular expression - hence queries like this one containing `/` would occasionally be tokenized incorrectly.

**Comment by laurencee** [comment]
Excellent!
