### ISSUE TITLE
Dashboard not showing 0 for "sum of all bars" when query returns no results

### ISSUE THREAD

**Issue by laurencee** [datalust/seq-releases#578]
**Seq version: 4.0.58**

We've been playing around some more with graphs/charts for our team but noticed one of them does not show the overlay sum in bar chart mode while the rest do.

![image](https://cloud.githubusercontent.com/assets/3850553/26660816/d698f58a-46bd-11e7-8648-606268f088d7.png)

```
select count(substring(@Message, 18, (length(@Message)) - 62)) as Server
from stream 
where (AppName like 'TPSConMan') and (@Message like 'GetMsg CQTcpBoss %')
group by substring(@Message, 18, (length(@Message)) - 62), time(1m)
limit 10000
```

**Comment by laurencee** [comment]
I didn't do a particularly good job with taking that screencap :P

**Comment by laurencee** [comment]
Ok so I played around with this a bit more and it appears that the overlay does display when there are some events in the period but if there weren't any then it doesn't display 0, it just displays nothing like in the screenshot above.

**Comment by nblumhardt** [comment]
Thanks for the report @laurencee - checking this one out 👍

**Comment by nblumhardt** [comment]
Fixed, thank you. The issue appeared when the underlying query uses a grouping in addition to `time()`, and there are no groups in the result set.
