### ISSUE TITLE
Raw JSON download fails

### ISSUE THREAD

**Issue by nskerl** [datalust/seq-releases#600]
Saw this error today while testing with some malformed events. It may be related to the empty message template. The ones without templates (no `@mt` provided to clef endpoint) throw a 500 when clicking on Raw JSON download.

`{"@t":"2017-07-18T04:01:00.8457194Z","@mt":"Error serving {RequestUrl} (token: {ErrorToken})","@l":"Error","@x":"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Serilog.Formatting.Json.JsonValueFormatter.WriteQuotedJsonString(String str, TextWriter output)\r\n   at Seq.Server.Storage.SeqClefFormatter.FormatEvent(StructuredEvent logEvent, TextWriter output, Boolean render)\r\n   at Seq.Server.Web.Api.Events.EventsModule.ToClef(IList`1 structuredEvents, Boolean render)\r\n   at Seq.Server.Web.Api.Events.EventsModule.GetSingle(String id)\r\n   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)","RequestUrl":"http://localhost:5341/api/events/event-3c96b2f0cd6608d4a13a010000000000?download=true&render=true&clef=true","ErrorToken":"807e6c3dadbf45aaac9f26f00425da06","RequestId":"1ced42db-8d0f-406e-b497-05fc379bfe3a"}`

![image](https://user-images.githubusercontent.com/782187/28300384-12db6ec0-6b34-11e7-87f7-d0de4b544100.png)

**Comment by nblumhardt** [comment]
Hi Nathan, thanks for the report, I'll take a look first thing.

**Comment by nblumhardt** [comment]
Thanks again for reporting this one. The issue is that the "download" link specifies the `?render` flag, and the code behind this doesn't handle this case.

To work around it, you can use `/api/events/{eventId}?clef=true` to download the CLEF-formatted event without `@m` field. Let me know if you need any further help with it.

Best regards,
Nick

**Comment by nskerl** [comment]
Great! thanks for the workaround.
