### ISSUE TITLE
Select default signals for new users

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#603]
When new users are created, they see an empty signal list and need to click "+" to discover all of the interesting stuff created by other team members.

The initial signal list, and default signals, should be able to be set for new users (perhaps as a global setting, if not per-user).

**Comment by nblumhardt** [comment]
Feedback on this is that the signal list and set of default signals will vary substantially between groups of users in an organization - a solution should take this into account.

**Comment by laurencee** [comment]
This would be extremely useful for us 👍 

Having to inform each new person about what good signals have already been created and getting them to add them is a bit of an overhead that shouldn't be necessary.

**Comment by nblumhardt** [comment]
In 4.2 we might not get all use cases, but should help with a few of them - a full "groups" feature would expand what we can do in the future.

Here's the first cut - _New User Defaults_:

![image](https://user-images.githubusercontent.com/342712/30014346-14b16796-918f-11e7-95af-ce687ff34cb9.png)

The "New User Defaults" screen allows a set of signals to be specified:

![image](https://user-images.githubusercontent.com/342712/30014386-352e236a-918f-11e7-9ffc-66aeb0571591.png)

When manually adding users, the list can be tweaked. This should be a better process than the current one, even if there's still some effort required:

![image](https://user-images.githubusercontent.com/342712/30014407-53a47830-918f-11e7-8bdf-3b2a23b35a23.png)

When users are automatically provisioned by AD or AAD, the defaults will be used as-is.

Feedback/thoughts welcome.

**Comment by laurencee** [comment]
That'll cover what I was looking for out of this 👍

**Comment by nblumhardt** [comment]
Awesome, thank you for the feedback.
