### ISSUE TITLE
Filters - `in` operator and array literals

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#610]
I would prefer to type:

```sql
@Level in ['Warning', 'Error', 'Fatal']
```

instead of the long-form `@Level = 'Warning' or ...`. The `in` operator feels like a missing piece of the filter/query language.

**Comment by nblumhardt** [comment]
![image](https://user-images.githubusercontent.com/342712/29103822-43d19bac-7d05-11e7-88c0-e3bf148c4db3.png)

**Comment by tsimbalar** [comment]
wait, but shouldn't it use parenthesis instead of square brackets ? something closer to SQL like : 
```
@Level in ('Warning', 'Error', 'Fatal')
```
... or support both ?

**Comment by nblumhardt** [comment]
I almost commented along these lines, too :-)

Yes, you're right regarding `in`, and we probably should support both.

I wanted to include array literal syntax along with this change, so `[1, 2, 3]` fills that role - unfortunately, parentheses `(1, 2, 3)` don't make an ideal array literal because of the ambiguity with `()` for grouping. I noticed that PostgreSQL uses `ARRAY[1, 2, 3]` for array literals, or alternatively a stringy syntax `'"{1, 2, 3}"'` - the JavaScript `[]` seems more natural for Seq, to me.

I'll revisit this as soon as I have a chance. Thanks for the input 👍
