### ISSUE TITLE
Graph data points link to events page without time filters set in Safari browser

### ISSUE THREAD

**Issue by happypup** [datalust/seq-releases#612]
After clicking on a data point in a graph (under dashboards) events page is shown without 'from' 'to' filters being set meaning that you are not taken to the data point.

This happens on Safari browser. It works in Chrome (on MAC) fine.

**Comment by nblumhardt** [comment]
Thank you for the report, we'll check this out.

**Comment by nblumhardt** [comment]
This was due to a date parsing difference between Safari and Chrome/Firefox/IE. Fix on the way for 4.2.

Thanks again, @happypup!
