### ISSUE TITLE
Add Seq Marketing Assets

### ISSUE THREAD

**Issue by Jaben** [datalust/seq-releases#613]
Requesting: Seq marketing assets. PNGs -- "Supports Seq" style buttons for OS projects (e.g. Papercut) with little links.

I specifically need some basic Seq PNGs for the YouTrack.Seq project.

Thanks Nick!

**Comment by nblumhardt** [comment]
Hey Jaben! I can send these through to you - would a simple Seq logo do the job? Can shoot you files via email if you let me know the background (light, I'm assuming) and size 👍 Cheers!

**Comment by Jaben** [comment]
Yes! Light would be 👍 Thanks Nick!

**Comment by nblumhardt** [comment]
Followed up via email, will close this but please let me know if I didn't reach you. Thanks!
