### ISSUE TITLE
Exclude `false` values from `count(expr)`

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#615]
See: https://docs.getseq.net/discuss/59a935f9b66c690019080959

Seq 4.1 permits `count(expr)` to count rows where `expr` is non-null. This is consistent with usual SQL count semantics, but not always useful.

For example, to determine the proportion of rows matching a criteria, it would be nice to accept:

```sql
select count(Yield > 0)/count(*) from stream
```

while two queries are necessary to do this today.

In Seq 4.2, we'll change semantics to exclude `false` values from the count. (It's easy to get the old semantics with expressions like `count(Yield is not null)`.

**Comment by Mike-EEE** [comment]
Woohoo!  Thank you much @nblumhardt and Team Seq!
