### ISSUE TITLE
Promoted Properties in Event Screen

### ISSUE THREAD

**Issue by mason-mcglothlin** [datalust/seq-releases#619]
We have certain properties that we apply to all of our events via applied properties on our API keys:

Application (specifically which program the log message originated in)
Platform (the broader product that the application is part of)
Environment (dev, testing, staging, production etc)

We heavily use these properties in our signals to filter down the events when we're looking for specific issues. But it'd be nice if these properties were to show up as an additional column on the Events page. That way when we're just monitoring the logs (not looking for anything specific) we can know important details about the logged event without having to expand it. Ideally the Events screen would be customizable so that each user can choose what properties they'd like to see.

**Comment by tsimbalar** [comment]
We are doing basically that too :)

To do that : 

- Create a new *signal* in which you add as **tags** the properties you want to see
![image](https://user-images.githubusercontent.com/160544/31501078-88494d34-af69-11e7-82b1-8e6fcfa383c2.png)


- Set this signal as a default signal for you profile
![image](https://user-images.githubusercontent.com/160544/31501124-ab5ef774-af69-11e7-80e8-bced9dd1a9df.png)

![image](https://user-images.githubusercontent.com/160544/31501134-b2e29bf4-af69-11e7-8e92-17b335c2bfe1.png)



- Notice that the properties you want are more visible whenever you access the events list
![image](https://user-images.githubusercontent.com/160544/31501190-d1fc809a-af69-11e7-8f8f-5926d6388b86.png)

Here is the original issue that covers it #379 .
There is an open issue to be able to assign it to other users : #603

**Comment by mason-mcglothlin** [comment]
That looks like what I need. But I can't seem to figure out the syntax for tags. Let's say I want to set the Application property as a tag. What should my signal look like to create the tag?

![image](https://user-images.githubusercontent.com/8096989/31502004-747a1eb0-af31-11e7-93d5-b1030030b3b5.png)

**Comment by mason-mcglothlin** [comment]
Ah, nevermind, figured it out. On a particular event, you have to expand the event, then click the green checkmark next to it, and hit "show as tag".

I think this could use a mention on the documentation site.

**Comment by nblumhardt** [comment]
Yes, that's correct :-) Glad this one is covered, please get in touch if you need any more help with it.
