### ISSUE TITLE
Error when processing a query with group by / Substring / IndexOf(regex)

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-releases#621]
Hi,

I'm trying to get some metrics about some events generated by SerilogWeb.Classic ... 

I have some events with a property `RawUrl` , and for some of them, and they look like those values : 
- `/App/v1/widgets`
- `/App/v1/widgets/catalog`
- `/App/v1/widgets/456`
- `/App/v1/foos/24`
- `/App/v1/foos/45/bar`

I am trying to get some statistics by *Url template* , that is, `/App/v1/foos/24` and `/App/v1/foos/456` share the same *template*, `/App/v1/widgets` is another one, `/App/v1/widgets/456` and `/App/v1/widgets/444` is another one.

In a first naive approach, I'm trying to group by a substring of the rawurl, stopping when I see the first `/{number}` .... 

I have tried the following query, but it fails : 
```sql
select count(*) as requests 
from stream 
where @EventType = 0x5FF28D57 
group by Substring(RawUrl, 0, IndexOf(RawUrl, /\/[0-9]/)) 
order by requests DESC 
limit 100
```

and I get the error message : `An unhandled error occurred while serving the request (token: 6539cf9aa59948d9b62ff75dc7b364e9).`

Same issue with :
```sql
select count(*) as requests 
from stream 
where @EventType = 0x5FF28D57 
group by Substring(RawUrl, 0, IndexOf(RawUrl, /\/\d/)) 
order by requests DESC 
limit 100
```

The following query works (without the constraint "a slash and then a digit"), but does not return what I want:
```sql
select count(*) as requests 
from stream 
where @EventType = 0x5FF28D57 
group by Substring(RawUrl, 0, IndexOf(RawUrl, /\d/)) 
order by requests DESC 
limit 100
```

(because from `/App/v1/widgets/456` it extracts `/App/v` )

Is there soemthing obvious I am missing here ?

**Comment by nblumhardt** [comment]
Thanks for the report, Thibaud.

The token in the error message makes it possible to find the error in the `C:\ProgramData\Seq\Logs` log files; I was able to reproduce it on my machine and got:

```
System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at ...
```

This is a silly bug at our end; I think you will be able to work around it by adding:

```sql
where IndexOf(RawUrl, /\/[0-9]/) >= 0
```

to your first query. Let me know if this helps. Thanks!

**Comment by tsimbalar** [comment]
Thanks, that's better :) 
I still don't manage to get exactly what I want to ... I'll create a more concrete issue with details of  what I'm trying to do, see if there is already a way of doing it that I haven't figured out ....
