### ISSUE TITLE
Given a property with a request URL, how can I group by Url Template ?

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-releases#622]
Hi,

this is more or less the continuation to my initial issue  #621  ... 

We are using [SerilogWeb.Classic](https://github.com/serilog-web/classic) + [SerilogWeb.Classic.WebApi](https://github.com/serilog-web/classic-webapi) on some of our Web APIs, and it's been really useful to track down the load and also chatty clients :) 

Now we are trying to extract information about the hotspots in our APIs, that is the API methods that are used the most and take the longest time, but because all we have is the URL, we are looking for a way to infer the *API Method* from the *invoked URL*... 

Basically, we have calls to URLs on the left, and would want to consider the Url templates on the right for our statistics ... 

| URL| URL Template |
| --- | --- |
| `/widgets/28` | `/widgets/{id}` |
| `/widgets/526` | `/widgets/{id}` |
| `/widgets/28/bars` | `/widgets/{id}/bars` |
| `/widgets/28/bars?active=true` | `/widgets/{id}/bars?active=true` |
| `/apps/17/users/45` | `/apps/{id}/users/{id}` |
| `/foos?ownerBar=45` | `/foos?ownerBar={id}` |
| `/users?like=john` | `/users?like={username}` |

We don't really need anything too fancy, and it's ok to hard code some patterns here and there .... 

I guess it would be possible to do that with lots of `Substring()` and `IndexOf()` etc, but that looks pretty tricky to get right, and the fact that `IndexOf()` returns `-1` when the pattern is not found makes it even harder to combine.

I think in this case, *string replacement* accepting a string or a regex would be helpful :) 

It would allow us to write something like : 
```sql
select count(*) as requests 
from stream 
where @EventType = 0x5FF28D57
group by Replace(RawUrl, /\/\d+\//, '/{id}/')
```

... or any other proposition that would help :)

**Comment by nblumhardt** [comment]
Interesting - this is analogous to how Serilog message templates work, and how event ids are assigned by Seq... I wonder; do you have any mechanism by which you could capture and compute the URI template client-side? Even hashing it to form a "URI id"?

I think the suggestion makes sense, but may be a bit of a specialized use case to get time allocated at this point, so any alternative approach like a client-side computation seems like it will achieve a solution faster.

Cheers!

**Comment by tsimbalar** [comment]
Actually I've been wondering about it ....

I'm using Web API with *Routting attributed*, so technically, we do have the *url template* available already in the form of  `[Route("api/v1/foos/{id}/bar")]` on top of our controller actions .... I'll see if I can figure out a way of extracting that and adding it as a property to the generated messages ... :crossed_fingers: 

Thanks !

**Comment by nblumhardt** [comment]
Ooooooooh.... a route template enricher, very cool! Good luck 👍

**Comment by tsimbalar** [comment]
I gave it a try in here serilog-web/classic-webapi#4 ...

**Comment by nblumhardt** [comment]
WebAPI PR merged; closing this one for now - thanks Thibaud!

**Comment by tsimbalar** [comment]
Just a note : it works great !

![image](https://user-images.githubusercontent.com/160544/35861009-8846b194-0b46-11e8-81a2-f64b6209b987.png)

![image](https://user-images.githubusercontent.com/160544/35861060-b53987bc-0b46-11e8-9a82-dd801a6a6324.png)
