### ISSUE TITLE
Signal expressions for app input, retention, charts

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-releases#633]
Apps, retention policies, and various other features in Seq can receive events from a signal.

Unfortunately, in Seq 4.1, the only way to send events from multiple signals to the same app is to configure multiple instances of the app. For example, I may want email notifications for errors in the production environment **and** the UAT environment.

Seq 4.2 will introduce "signal expressions" that describe an input signal in terms of another. The email scenario would be implemented logically as _Errors intersect (Production union UAT)_.

In the first version of the feature, the groupings like _Production union UAT_ will be inferred automatically based on the underlying filters, based on the knowledge that two filters `Environment = 'Production'` and `Environment = 'UAT'` can only ever be mutually exclusive (see #604). In future the expression editor can be extended to permit arbitrary groupings.

**Comment by nblumhardt** [comment]
![image](https://user-images.githubusercontent.com/342712/33358107-4f73c02e-d512-11e7-832f-4482656eddd6.png)

This is coming in the next pre-release build :-)

**Comment by tsimbalar** [comment]
Hi,

this looks interesting, but I have to say I don't understand completely what this feature is about 🤔   and how it relates to #604 ...

>  Seq 4.2 will introduce "signal expressions" that describe an input signal in terms of another

what does it look like to the user ? is it a field where you select multiple existing signals ?  is it a special kind of field in the UI ? 

Regarding the screenshot, I don't really undestand the use of **in** and the fact that it can be used multiple times ... what would `@Level=Error in Environment=Prod|UAT|Test in App=WebApp1|WebApp2` mean ?


I guess I'll have to take a look at the next pre-release to wrap my head around it ;)

**Comment by nblumhardt** [comment]
Thanks for dropping by, @tsimbalar!

It's a bit of an obtuse description, sorry - the feature's actually pretty simple and described almost completely by the screenshot: previously it was impossible to send  `Environment=Prod|UAT|Test` to the same app instance. Now, if we detect that the selected signals represent different values for the same property, we'll group them up and "union" them instead of "intersecting" them.

The choice of the separator `in` is a tough one; we only just today switched over from `and` because it was confusing in other ways; alternative suggestions welcome.

(I'm not sure that makes it any clearer, actually; it seems very natural when you use it! 😄)

The relationship to #604 is that the "quick selectors" for property values use the same mechanism: Seq will detect when a group of signals choose values for a particular property, and group them up/"union" the events that match them.

**Comment by tsimbalar** [comment]
Thanks for taking the time to clarify it ! :)

What I hadn't understood is that there is really only just one "input" in the UI that is a signal, and Seq will do the rest and show "grouping" where it makes sense. I had understood it was the user's job to say "here is a list of signal on which I want a **OR** ... but those ones are a **AND** etc".

Maybe UI-wise it would make it clearer if the *OR*ed signals were **stacked** on top of each other instead of **next** to each other.... that is "left-to-right" means *AND* and "top-down" means OR, a bit like in graph representations of _context-free grammars_ (like http://homepages.abdn.ac.uk/k.vdeemter/pages/teaching/NLP/practicals/JSGFGrammar_files/commandGrammar.jpg even though it's not really comparable).

Anyway, that's just a suggestion and I can imagine it's a pain to change that kind of UI components :p

**Comment by Suchiman** [comment]
I would have probably gone with `and` and `or`, justifying that they apply logically to the conditions of the defined signals, not the results.
So the conditions of `signal1` `and` `signal2`, logically results in an result intersection.
Same for `or` where or'ing the conditions of signals results in an union.

**Comment by tbolon** [comment]
It's a really nice improvement.

Currently, we have developed a custom email notification app where settings are hard-coded, so our users can simply subscribe to a signal without having to enter SMTP settings. But this could allow them to use multiple apps without the need to configure them for each signal.

**Comment by nblumhardt** [comment]
@tsimbalar @Suchiman @tbolon thanks for the feedback 👍 

The major problem with `and` is that if you see a signal like `Errors **and** Warnings`, it's easy to misread that as having the events from both the Errors and Warnings signal, where, in reality, this would be an empty set (no event can be both an error and a warning..). Hence the switch to `in`, which reads strangely in some cases, but doesn't have as much ambiguity. We also considered more esoteric options, like icons, the Unicode "set intersection" symbol, and so-on, but none were obviously better than `in`.

@tbolon #566 should also help with the scenario you describe.
