### ISSUE TITLE
Signal Groups : when 2 signals have same name, clicking the first selects the second

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-releases#637]
Seen on Seq 4.2.280-pre .

I may have found a weird edge case with signal groups (playing around with #604  ) :p
I have created 2 signals with name `Errors` .... they now appear under the same signal group .

![image](https://user-images.githubusercontent.com/160544/33707716-a12cc664-db38-11e7-82be-b449e8fc1973.png)

If I hover the first signal ...
![image](https://user-images.githubusercontent.com/160544/33707752-c83c6b88-db38-11e7-9207-4b06a1735d34.png)
... and click it , the second signal is actually selected and highlighted
![image](https://user-images.githubusercontent.com/160544/33707779-dd9945f0-db38-11e7-9341-9cce74df623e.png)

If I click the first signal again, it does get selected though ... 
![image](https://user-images.githubusercontent.com/160544/33707866-207bb178-db39-11e7-9384-2bd53747903e.png)

As I said, that's quite an edge case, but well ;)

**Comment by nblumhardt** [comment]
Thanks for the report. This is due to some instability in how we sort signals - we'll get this patched up for the next preview 👍
